config/routes.rb
WeightTracker::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/help"

  root to: 'static_pages#home'

  match '/help',  to: 'static_pages#help'
  match '/about', to: 'static_pages#about'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "Weight Trackr"
		if page_title.empty?
			base_title
		else
			"#{page_title} - #{base_title}"
		end		
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Weight Trackr", root_path, id:"logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Help", help_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
    <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

	<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

	<%= render 'layouts/header' %>

	<div class="container" role="main">
		<%= yield %>
	

		<footer>

		</footer>

	</div> 

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About")	%>
<h1>About Weight Trackr</h1>
<p>
	Weight Trackr is a simple way to allow you to keep track of some key 
	body composition metrics that allow you to go beyond the traditional 
	weight measurement apps. 	
</p>
<p>
	Instead you can now keep track of metrics such as:
</p>
<ul>
	<li>Total Weight</li>
	<li>Muscle Mass%</li>
	<li>Body Water%</li>
	<li>Bone Weight</li>
	<li>Body Fat %</li>
</ul>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")	%>

<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to Weight Trackr</h1>

	<h2>
		Weight Trackr is a simple web application that allows you to quickly keep track of your bodies composition metrics over time.
	</h2>

	<%=	link_to "Sign up now", "#", class: "btn btn-large btn-primary" %>
</div>